//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RestaurantManagerSevice
{
    using System;
    using System.Collections.Generic;
    
    public partial class Bill_info
    {
        public int id { get; set; }
        public Nullable<int> id_bill { get; set; }
        public string customer_name { get; set; }
        public string employee_name { get; set; }
        public Nullable<int> id_drink { get; set; }
        public Nullable<int> id_food { get; set; }
        public Nullable<double> count_food { get; set; }
        public Nullable<double> count_drink { get; set; }
    
        public virtual Bill Bill { get; set; }
        public virtual Drink Drink { get; set; }
        public virtual Food Food { get; set; }
    }
}
